# -*- cmake -*-
if (LLCHARACTER_CMAKE_INCLUDED)
  return()
endif (LLCHARACTER_CMAKE_INCLUDED)
set (LLCHARACTER_CMAKE_INCLUDED TRUE)

set(LLCHARACTER_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/llcharacter)

set(LLCHARACTER_LIBRARIES llcharacter)
