# -*- cmake -*-
if (LLCONVEXDECOMPOSITION_CMAKE_INCLUDED)
  return()
endif (LLCONVEXDECOMPOSITION_CMAKE_INCLUDED)
set (LLCONVEXDECOMPOSITION_CMAKE_INCLUDED TRUE)

include(Prebuilt)

set(LLCONVEXDECOMP_INCLUDE_DIRS ${LIBS_PREBUILT_DIR}/include)

include(HACD)
