# -*- cmake -*-
if (LLINVENTORY_CMAKE_INCLUDED)
  return()
endif (LLINVENTORY_CMAKE_INCLUDED)
set (LLINVENTORY_CMAKE_INCLUDED TRUE)

set(LLINVENTORY_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/llinventory)

set(LLINVENTORY_LIBRARIES llinventory)
