# -*- cmake -*-
if (MEDIAPLUGINBASE_CMAKE_INCLUDED)
  return()
endif (MEDIAPLUGINBASE_CMAKE_INCLUDED)
set (MEDIAPLUGINBASE_CMAKE_INCLUDED TRUE)

set(MEDIA_PLUGIN_BASE_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/media_plugins/base/)

set(MEDIA_PLUGIN_BASE_LIBRARIES media_plugin_base)
